name: Build, Push Helm Chart & build image
on:
  workflow_dispatch:
    inputs:
      chart_tag:
        description: 'Force Version Override?'
        required: false
        type: string
        default: ""
      chart_overwrite:
        description: 'Force Chart Overwrite?'
        required: true
        type: boolean
        default: false
      git_branch:
        description: 'Git branch to checkout'
        required: false
        type: string
        default: ""
      pre_build_script:
        description: 'Pre-build script to run'
        required: false
        type: string
        default: ""
      is_lib_chart:
        description: 'Is this a library chart?'
        required: false
        type: boolean
        default: false
      custom-image-name:
        description: 'Custom image name'
        required: false
        type: string
        default: ""
      build-target:
        description: 'Docker build target'
        required: false
        type: string
        default: ""
      docker-build-args:
        description: 'Docker build arguments'
        required: false
        type: string
        default: ""
      dockerfile-path:
        description: 'Path to Dockerfile'
        required: false
        type: string
        default: "Dockerfile"
      docker-arch:
        description: 'Docker architectures to build'
        required: false
        type: string
        default: "linux/amd64,linux/arm64"
  push:
    tags:
      - 'v?*.*.*'
    branches:
      - development
      - gamma
    paths:
      - 'chart/**'         
  pull_request:
    types:
      - opened
      - synchronize

# Global environment variables
env:
  DOCKER_HUB_USER: "owolabi16" # VERIFY: Change to your Docker Hub username
  GPT_CHART_DIR: "chart"
  HELM_TEMPLATE: "template.yaml"
  REGISTRY: "ghcr.io"
  CHART_OVERWRITE: ${{ inputs.chart_overwrite }}

# Set default permissions
permissions:
  contents: read
  packages: write

jobs:
  build-chart:
    runs-on: ubuntu-latest
    outputs:
      chart-version: ${{ steps.extract-version.outputs.chart-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.git_branch }}
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}

      - name: Run Pre-Build User-defined script
        if: inputs.pre_build_script != ''
        run: bash -c '${{ inputs.pre_build_script }}'

      - name: Generate Docs
        continue-on-error: true
        uses: docker://jnorwood/helm-docs:v1.11.0
        with:
          entrypoint: helm-docs
          args: -g $(basename ${{ env.GPT_CHART_DIR }})
      
      - name: Install Dependencies
        run: helm dep build ${{ env.GPT_CHART_DIR }} --skip-refresh
      
      - name: Helm Lint
        run: helm lint ${{ env.GPT_CHART_DIR }}
      
      - name: Generate template.yaml
        if: ${{ !inputs.is_lib_chart }}
        run: helm template ${{ env.GPT_CHART_DIR }} > ${{ env.GPT_CHART_DIR }}/${{ env.HELM_TEMPLATE }} && cat ${{ env.GPT_CHART_DIR }}/${{ env.HELM_TEMPLATE }}
      
      - name: KubeVal Kubernetes Objects
        if: ${{ !inputs.is_lib_chart }}
        run: >
          docker run --rm -v $(pwd)/${{ env.GPT_CHART_DIR }}:/data
          cytopia/kubeval
          ${{ env.HELM_TEMPLATE }}
          --output=stdout
          --strict
          --ignore-missing-schemas
      
      - name: Clean up template file
        if: ${{ !inputs.is_lib_chart }}
        run: rm -f ${{ env.GPT_CHART_DIR }}/${{ env.HELM_TEMPLATE }}
      
      - name: Get Chart Name from Chart.yaml
        run: echo "CHART_NAME=$(yq eval .name ${{ env.GPT_CHART_DIR }}/Chart.yaml)" >> $GITHUB_ENV
      
      - name: Get Chart Tag/version from Chart.yaml if not inputted
        id: extract-version
        run: |
          if [ "${{ inputs.chart_tag }}" == "" ]; then
            VERSION=$(yq eval .version ${{ env.GPT_CHART_DIR }}/Chart.yaml)
          else
            VERSION="${{ inputs.chart_tag }}"
          fi
          echo "CHART_TAG=$VERSION" >> $GITHUB_ENV
          echo "chart-version=$VERSION" >> $GITHUB_OUTPUT
      
      - name: Chart Registry Overwrite Protection
        if: ${{ inputs.chart_overwrite == false }}
        run: |
          if helm pull oci://${{ env.REGISTRY }}/chart/${{ env.CHART_NAME }} --version ${{ env.CHART_TAG }} 2>/dev/null; then
            echo "Chart ${{ env.CHART_NAME }}:${{ env.CHART_TAG }} already exists and overwrite is disabled."
            exit 1
          fi
      
      - name: Release Helm Chart
        uses: appany/helm-oci-chart-releaser@v0.4.0
        with:
          name: ${{ env.CHART_NAME }}
          repository: owolabi16/charts # VERIFY: Change to your repository
          tag: ${{ env.CHART_TAG }}
          path: ${{ env.GPT_CHART_DIR }}
          registry: ghcr.io
          registry_username: Owolabi16 # VERIFY: Change to your GitHub username
          registry_password: ${{ secrets.PAT_TOKEN }}
        env:
          HELM_EXPERIMENTAL_OCI: 1      

  build-image:
    runs-on: ubuntu-latest
    needs: build-chart # Fixed circular dependency
    outputs:
      docker-tag: ${{ steps.meta.outputs.version }}
      docker-repo: ${{ steps.docker-repo.outputs.DOCKER_REPOSITORY }}
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Set Docker Repository Variable
        run: echo "DOCKER_REPOSITORY=${{ env.DOCKER_HUB_USER }}/$( echo ${{ github.repository }} | awk -F '/' '{print $2}' | awk '{print tolower($0)}' )" >> $GITHUB_ENV
      
      - name: Set Docker Repository Output
        id: docker-repo
        run: echo "DOCKER_REPOSITORY=${{ env.DOCKER_HUB_USER }}/$( echo ${{ github.repository }} | awk -F '/' '{print $2}' | awk '{print tolower($0)}' )" >> $GITHUB_OUTPUT
      
      - name: Set Repository Owner
        run: echo "REPO_OWNER=$( echo ${{ github.repository_owner }} | awk '{print tolower($0)}' )" >> $GITHUB_ENV
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}   
      
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ inputs.custom-image-name != '' && format('{0}/{1}', env.DOCKER_HUB_USER, inputs.custom-image-name) || env.DOCKER_REPOSITORY }}
            ghcr.io/${{ env.REPO_OWNER }}/${{ inputs.custom-image-name != '' && inputs.custom-image-name || github.event.repository.name }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr,suffix=${{ inputs.build-target != '' && format('-{0}', inputs.build-target) || ''}}
            type=semver,pattern={{version}},suffix=${{ inputs.build-target != '' && format('-{0}', inputs.build-target) || ''}}
            type=semver,pattern={{major}}.{{minor}},suffix=${{ inputs.build-target != '' && format('-{0}', inputs.build-target) || ''}}
            type=semver,pattern={{major}},suffix=${{ inputs.build-target != '' && format('-{0}', inputs.build-target) || ''}}
            type=sha
            type=raw,value=${{inputs.build-target}}
           
      - name: Build and push
        id: build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          build-args: ${{ inputs.docker-build-args }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ${{ inputs.dockerfile-path }}
          platforms: ${{ inputs.docker-arch }}
          pull: true
          no-cache: false
          cache-from: type=registry,ref=ghcr.io/${{ env.REPO_OWNER }}/cache:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ env.REPO_OWNER }}/cache:buildcache,mode=max
          target: ${{ inputs.build-target }}